README.md

The pipe in the sample Regex was breaking the Makrdown table on the [Webpack docs page](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/).
Solution is based on this -- https://github.com/gitlabhq/gitlabhq/issues/1238

Fix GFM table issue

---

README.md

@bebraw - As part of the effort to reach compliance with JSF and get the CLA bot enabled, maintainers need to be clearly displayed.
While I was at it, I did the updates to the readme using the template chosen for the standards effort.

docs(readme): updates for JSF CLA

---

package.json
src/index.js

- Bumps uglify-js peerDep to ^2.8.0
Closes #15

fix(uglifyJS): use Compress API not ast.transform

---

README.md

Markdown doesn't support having markdown inside of HTML, so the UglifyJS link wasn't rendering properly.  Now it will.

Fix the UglifyJS2 README link

---

README.md

As @bebraw noted in https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/33#issuecomment-302948338, the plugin is not yet compatible with V3 of UglifyJS2, so the Readme should point to the last working version for now.

Updated readme to reflect last compatible version of UglifyJS2#harmony

---

package.json
yarn.lock

Also add webpack 3 to peerDependencies.
Should fix #44

fix(package): mv uglify2 to `dependencies` && update `peerDependencies`

---

src/index.js

So, as a proof of concept... I created this: https://github.com/hulkish/dummy
Pull that repo, then run:
```
yarn
node scripts/profile.js
```
You will see an output which looks like:
```
untouched_node@v6.11.0 compile...
untouched_node@v6.11.0 files length 68
untouched_node@v6.11.0 profiler.startProfiling()
untouched_node@v6.11.0: 27549.784ms
untouched_node@v6.11.0 profiler.stopProfiling()
untouched_node@v6.11.0 profile.export()
untouched_node@v6.11.0 profile saved: /Users/shargrove/dev/repos/dummy/untouched_node@v6.11.0.uglifyjs-webpack-plugin.cpuprofile
forEach_WeakSet_node@v6.11.0 compile...
forEach_WeakSet_node@v6.11.0 files length 68
forEach_WeakSet_node@v6.11.0 profiler.startProfiling()
forEach_WeakSet_node@v6.11.0: 14367.834ms
forEach_WeakSet_node@v6.11.0 profiler.stopProfiling() …
```

refactor: changed `__UglifyJsPlugin` dereference to use `WeakSet` instead

---

package-lock.json
package.json
src/index.js
test/__snapshots__/es2015.test.js.snap
test/__snapshots__/supports-multicompiler.test.js.snap
test/helpers.js
test/supports-multicompiler.test.js

Fixes #73
**Update:** So, it looks like this issue just *magically fixed itself*. That, said - I'd like to still include the added tests and upgrade to `uglify-es@3.0.24`.

test: add test for `MultiCompiler` usage

---

package-lock.json
package.json

Fixes: #120 
This should be able to solve the licensing issue: both `cacache` and `ssri` have been relicense to ISC (according to current npm policy), and released as a semver-major bump.
This might supersede #121

fix(deps): cacache@10 with ISC licence

---

src/uglify/minify.js

fix(minify): `nameCache` assignment (`uglifyOptions.nameCache`)

---

src/index.js
test/__snapshots__/exclude-option.test.js.snap
test/exclude-option.test.js
test/fixtures/excluded1.js
test/fixtures/excluded2.js

A simple demo of the problem can be found [here](https://github.com/rszewczyk/uglifyjs-webpack-plugin/tree/demo-the-problem/demo).
The expected behavior is that chunks with a filename that match the [given pattern](https://github.com/rszewczyk/uglifyjs-webpack-plugin/blob/demo-the-problem/demo/webpack.config.js#L13) will be excluded from uglify. This was the behavior exhibited by __0.4.6__. The actual behavior is that all chunks are uglified.
It looks like the problem is that the [options used to filter](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/c425f3cb9612f4259af681d9c4aa1547f0d622be/src/index.js#L110) what chunks are processed, [do not include](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/c425f3cb9612f4259af681d9c4aa1547f0d622be/src/index.js#L36- …

fix(index): exclude is ignored (`options.exclude`)

---

README.md

The code samples in the README refer to the plugin as `UglifyJSPlugin` instead of `UglifyJsPlugin` which is incorrect (see export [here](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/index.js#L246). This PR fixes the README.

docs(README): rename `UglifyJSPlugin` to `UglifyJsPlugin` in examples

---

README.md
src/uglify/minify.js
test/__snapshots__/extract-comments-options.test.js.snap
test/extract-comments-options.test.js

- Fixes https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/84
Improves tests around `extractComments` option

fix: pass of `{Boolean|Function}` parameters being ignored (`options.extractComments`)

---

src/uglify/index.js

- Fixes #118
In Windows 10 if `parallel: true` is set then the parallel worker processes can stall and the build never completes.
The minify request is successfully sent from the plugin to the dist/uglify/worker.js which then minifies the file.
The forked worker returns the result to the plugin via the Node process.send() IPC call, but the parent plugin never receives the request from the worker.
The `forked.child.on('message', this.receive.bind(this))` event in worker-farm/lib/farm.js is never invoked which causes the build to stall.
If we change the worker-farm to use `maxConcurrentCallsPerWorker: 1` it will prevent the parent from queuing multiple requests via IPC to the workers. It waits until it receives a response from the worker, then it dispatches the next file to minify. This …

fix(index): set `maxConcurrentCallsPerWorker` to 1 (`options.parallel`)

---

src/index.js
src/uglify/minify.js
test/__snapshots__/extract-comments-options.test.js.snap
test/all-options.test.js
test/ecma.test.js
test/extract-comments-options.test.js
test/uglify/worker.test.js

Fix comments behavior:
1. by default `output.comments` should be false (https://github.com/mishoo/UglifyJS2#output-options and https://github.com/webpack/webpack/pull/5940).
2. `extractComments: true` should be interpreted as `/^\**!|@preserve|@license|@cc_on/` (https://github.com/webpack/webpack/pull/5940)

fix: comments behavior (`options.uglifyOptions.comments/options.extractComments`)

---

package-lock.json
package.json

There are a couple of important fixes in `3.2.0` that should make it the new minimum:
- https://github.com/mishoo/UglifyJS2/issues/2497
- https://github.com/mishoo/UglifyJS2/issues/2496

chore(package): update `uglify-es` v3.1.3...3.2.0

---

package.json
test/__snapshots__/ecma.test.js.snap

related to this issue: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/187
uglify-es version 3.2.0 doesn't support `const` and arrow-function. In my case, this causes build failure when I try to make a production bundle for deployment

chore(package): update `uglify-es` v3.2.0...v3.2.1

---

test/cache-options.test.js

Remove cache after each describe, because the next test can use the previous cache. Also remove `othercacheDir` cache, because they not removed after test.

tests: remove `cache` directory after tests

---

package.json

This is for fixing the uglify-es dependency, as the new 3.3.x versions breaks up all Angular builds.
See [here for Angular](https://github.com/angular/angular/issues/21173) and [here for Angular CLI](https://github.com/angular/angular-cli/issues/8997)

fix(package): use exact `uglify-es` version (`dependencies`)

---

src/index.js

fix(index): don't pass `compilation` as an argument to `UglifyJsPlugin.buildError`

---

package.json
src/index.js

This PR updates `uglifyjs-webpack-plugin` to use `.tap()` and `.tapAsync()` isntaed of `.plugin()` and use the new Tapable API in `webpack@webpack/webpack#next`. 
Looks like prettier did some auto updating etc.

refactor(index): upgrade `compiler.plugin` to the new plugin system (`tapable`)

---

src/index.js
test/__snapshots__/cache-options.test.js.snap
test/cache-options.test.js

fix(index): reduce memory consumption (`cacheKey.hash`)

---

README.md
src/uglify/minify.js
test/__snapshots__/uglify-options.test.js.snap
test/uglify-options.test.js

Also sort options as uglify docs.
Add all options and tests. In next PR i try to implement internal cache for `nameCache` for increase perf :+1:

feat(minify): add missing `toplevel`, `nameCache`, `keep_classnames`, `keep_fnames` and `safari10` options (`uglifyOptions`)

---

src/index.js

- Fixes #240 
- Fixes #241 
Fixes a typo in the webpack 4 Plugin API Compat branch

fix(index): typo `buildMobule` => `buildModule`

---

src/index.js
test/__snapshots__/extract-comments-options.test.js.snap
test/extract-comments-options.test.js

- Fixes #181
license path right now always relative to file where from extract

fix(index): correct `[name].js.LICENSE` file path (`options.extractComments`)

---

src/index.js
test/__snapshots__/test.test.js.snap
test/fixtures/async-import-export/async-dep.js
test/fixtures/async-import-export/entry.js
test/fixtures/entry.mjs
test/fixtures/import-export/async-dep.js
test/test.test.js

fix(index): relax default in asset names `{RegExp}` (`options.test`)

---

package.json

- Fixes https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/246
On the 10.0.4 version of cacache, ssri was upgraded, where was resolved the vulnerability

fix(package): update`cacache` v10.0.1...10.0.4 (`dependencies`)

---

package-lock.json
package.json
test/__snapshots__/invalid-options.test.js.snap

Upgrade the `schema-utils` dependency to stop peer dependency warnings with webpack 4.

fix(package): update `schema-utils` v0.4.3...0.4.5 (`dependencies`)

---

src/index.js

https://regex101.com/r/SJm7SO/2
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/251#issuecomment-372731973

fix(index): correct default asset name `{RegExp}` (`options.test`)

---

src/index.js
test/__snapshots__/extract-comments-options.test.js.snap
test/__snapshots__/invalid-options.test.js.snap
test/extract-comments-options.test.js

fix(index): don't remove legal comments by default (`options.extractComments`)

---

src/index.js
src/utils/index.js
test/__snapshots__/source-map-options.test.js.snap
test/parallel-options.test.js
test/source-map-options.test.js
test/utils/index.test.js

fixes #261
Also refactor tests

fix: don't handle invalid source map

---

src/index.js
test/__snapshots__/all-options.test.js.snap

Just refactor. Each warning should be push separately, it is allow filter some warning after uglify plugin from `compilation.warnings`, also it is improve readability warning, `stack` in one line looks horrible

refactor: push each `warning` separately

---

src/index.js

We create source map on each `file` and it is increase memory usage very very very lagre, but using `sourceMap` only for error. Let's create `sourceMap` only when erros/warnings were throws.

perf: reduce memory usage

---

src/index.js
src/utils/index.js
test/__snapshots__/source-map-options.test.js.snap
test/utils/index.test.js

fix: improve `isSouceMap` check

---

src/index.js

fixes #286
Looks we already have tests around error/warning

fix: perf regression

---

README.md
src/index.js
src/uglify/minify.js
test/__snapshots__/uglify-options.test.js.snap
test/fixtures/inline-optimization.js
test/uglify-options.test.js

fixes #307 fixes #264
Also we have problem with using option as object, they rewrited after first run.
Also improve readme
A lot of new tests

fix: disable inline optimization by default

---

src/index.js
test/__snapshots__/all-options.test.js.snap

fixes #281  
> Before: single warning for an asset, After: each warning separate
Before: info about the asset, After: information missing
Before: note about UglifyJS, After: no info
1. Each warning separate, it is allow filtering `compilation.warning` for plugins and who run webpack using own script (i have many questions in gitter how it is better do and one warning on an assets is best solution)
2. Add information about the asset
3. Add information about `UglifyJS`

fix: return missing important information

---

src/index.js
test/all-options.test.js

Also add tests when source map exists and doesn't exist

fix: no warning when `warningsFilter` return false

---

README.md
src/index.js
src/options.json
src/uglify/index.js
test/__snapshots__/cache-options.test.js.snap
test/cache-options.test.js

feat: `cacheKeys` option

---

README.md
package-lock.json
package.json
src/index.js
src/options.json
src/uglify/Runner.js
src/uglify/minify.js
test/__snapshots__/minify.test.js.snap
test/fixtures/minify/es5.js
test/fixtures/minify/es6.js
test/minify.test.js

:star: 
One question: what do with extracting comment for custom minify function, if people use `uglify-js`/`terser` our logic https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/uglify/minify.js#L45 is work good, maybe we should export this function to avoid copy/paste this code

feat: support `minify` function option

---

README.md
package-lock.json
src/uglify/worker.js
test/__snapshots__/minify.test.js.snap
test/minify.test.js

fix: all nodejs globals avaliable inside `minify` function

---

src/uglify/Runner.js

fix(uglify/Runner): `cpus` length in a chroot environment (`os.cpus()`)

---

src/index.js

In webpack@5, `chunks` is a `Set` and thus should be converted to an array.
n/a
This change makes the plugin compatible with webpack 4 and 5.

fix(index): handle `chunks` provided as a `{Set}`

---

src/index.js
src/minify.js
test/__snapshots__/extractComments-option.test.js.snap
test/extractComments-option.test.js
test/fixtures/comments-3.js
test/fixtures/comments-4.js

Dedupe extracted comments
No
No

fix: dedupe extracted comments

---

src/TaskRunner.js

fix: fallback for cache directory
No
No

fix: fallback for cache directory

---

package.json
src/TaskRunner.js

Disable parallel on WSL
No
We should migrate on `jest-worker` in future

fix: disable parallel on WSL

---

src/index.js
src/minify.js
test/__snapshots__/sourceMap-option.test.js.snap
test/__snapshots__/worker.test.js.snap
test/sourceMap-option.test.js

better source map generation
No
No

feat: generate higher quality SourceMaps
