- README.md
Documentation for webpack/webpack#4134
> Add documentation for the extractComments option

- README.md
> Clarify documentation about mangling

- ISSUE_TEMPLATE.md
> docs(ISSUE_TEMPLATE): rm redundant file

- README.md
I think this is no longer true.
> docs(README): update install instructions

- README.md
> docs(README): add `beta` notice

- README.md
> docs(README): add missing comma

- README.md
> docs(README): update description, fix format && typo

- README.md
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/index.js#L26
> docs(README): Fix default value (`options.test`)

- README.md
Add missing closing tag to make parsing this easier on webpack.js.org.
> docs(README): fix closing tag

- README.md
> docs(README): use unescaped char

- README.md
> docs(README): rm `beta` install reference

- package-lock.json
- package.json
Just update `source-map` package
> chore(package): update `source-map` v0.5.6...0.6.1

- src/index.js
- test/__snapshots__/source-map-options.test.js.snap
- test/source-map-options.test.js
- Simplify logic based on https://github.com/webpack/webpack-sources/blob/91862553dc108e897ec24ece7b5bd8aae42620e5/lib/Source.js#L24
- Add tests
- Fixes #111
> fix(index): ensure to nullify `inputSourceMap` if `sourcemap` is unavailable (`devtool`)

- src/index.js
- test/__snapshots__/cache-options.test.js.snap
Ref: https://github.com/webpack/webpack/pull/6549
> perf(index): use `md4` instead `md5` for content hasing

- test/__snapshots__/invalid-options.test.js.snap
> test(invalid-options): update snapshot

- README.md
> >=, not =<

- README.md
> docs(README): fix broken markdown

- package-lock.json
> chore(deps): update `package-lock.json`

- README.md
Update the example snippet to v4
https://webpack.js.org/plugins/uglifyjs-webpack-plugin/
> misc(readme) update snippet to webpack v4

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/chunkFilter-option.test.js.snap
- test/__snapshots__/validation.test.js.snap
- test/chunkFilter-option.test.js
- test/validation.test.js
Allowing to filter `chunks`
fixes #21
No
No
> feat: `chunkFilter` option for filtering chunks

- src/index.js
- test/__snapshots__/minify-option.test.js.snap
- test/minify-option.test.js
Backport from terser plugin
No
No
> fix: don't crash when no extracted comments

- .eslintrc.js
- .prettierrc
- package-lock.json
- package.json
- test/minify-option.test.js
- test/worker.test.js
> chore(defaults): update

- src/index.js
Invalidate cache after changing nodejs version
No
No
> fix: invalidate cache after changing node version
